added alert
ritikaawasthy/tranqUIlity pull request #1
Opened 2022-02-08 19:37 UTC by ritikaawasthy

2022-02-09 13:55 UTC, abhisheksahani-nova requested changes

2022-02-09 13:55 UTC, abhisheksahani-nova commented on css/documentation/styles.css
> +  color: grey;
Use color variables for all color

2022-02-09 14:24 UTC, anshulraheja approved these changes
Suggestion: 
1. Add some space between the alert icon (span) and content (p)
2.  Use little dark shades for content (p) inside the colored alerts.

2022-02-09 14:38 UTC, dhruvin25799 commented
Looks good, just a minor suggestion to change the text color for colored alerts, having the same shade of color for text reduces visibility.

2022-02-09 15:05 UTC, Sahil25061999 commented
Overall good code, just a suggestion variable names can be more explicit and spacing between and the text and icons can be increased.

2022-02-10 06:57 UTC, ritikaawasthy commented
> Looks good, just a minor suggestion to change the text color for colored alerts, having the same shade of color for text reduces visibility.

I've made the text color slightly darker for colored alerts to improve the visibility, let me know if this work.

2022-02-10 08:58 UTC, sumitk-singh commented
overall it look good to me

2022-02-11 21:26 UTC, merged